In [1]:

import time
import os
import shutil
import pandas as pd
from datetime import datetime
from dateutil import tz
import warnings
import itertools

import math
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split



In [2]:
# Remove the NaN rows and columns

def removeNaN(curr_feat_1, curr_feat_2):
    curr_feat_1_nan = np.array([])  # numpy.float64
    curr_feat_2_nan = np.array([])  # numpy.float64
    posi = 0
    # *** Check for and remove the Nan rows in from ONLY [curr_feat_2] feature rows
    for posi in range(len(curr_feat_2)):
        if not (math.isnan(curr_feat_2[posi])):# and not(math.isnan(curr_feat_1[posi]))):
            curr_feat_1_nan = np.append(curr_feat_1_nan, curr_feat_1[posi])
            curr_feat_2_nan = np.append(curr_feat_2_nan, curr_feat_2[posi])
            if (posi < 10):
                print(curr_feat_2_nan[posi])
        if (math.isnan(curr_feat_1[posi])):
            # curr_feat_1_nan = np.append(curr_feat_1_nan, curr_feat_1[posi])
            # curr_feat_2_nan = np.append(curr_feat_2_nan, curr_feat_2[posi])
            if (posi < 10):
                print(curr_feat_2_nan[posi])
    return curr_feat_1_nan, curr_feat_2_nan

#### Import .csv dataset into pandas
print('Importing Data Now')

#filename = '/Users/Mandala/PycharmProjects/ML_Project/windowing_results.csv'
filename = 'skin_conductance_new.csv'

# Read data from csv file 
df_feat = pd.read_csv(filename)
df_keys = df_feat.keys()



Importing Data Now


In [3]:
df_feat

Unnamed: 0                   Unnamed: 0.1  GSR #           start_time  \
0               0  GSR1_GSR_Skin_Conductance_CAL      1  2019-11-21 09:35:27   
1               1  GSR1_GSR_Skin_Conductance_CAL      1  2019-11-21 09:35:28   
2               2  GSR1_GSR_Skin_Conductance_CAL      1  2019-11-21 09:35:29   
3               3  GSR1_GSR_Skin_Conductance_CAL      1  2019-11-21 09:35:30   
4               4  GSR1_GSR_Skin_Conductance_CAL      1  2019-11-21 09:35:31   
...           ...                            ...    ...                  ...   
10286       10286  GSR6_GSR_Skin_Conductance_CAL      6  2019-11-21 11:00:35   
10287       10287  GSR6_GSR_Skin_Conductance_CAL      6  2019-11-21 11:00:36   
10288       10288  GSR6_GSR_Skin_Conductance_CAL      6  2019-11-21 11:00:37   
10289       10289  GSR6_GSR_Skin_Conductance_CAL      6  2019-11-21 11:00:38   
10290       10290  GSR6_GSR_Skin_Conductance_CAL      6  2019-11-21 11:00:39   

                  end_time  gsr_mean  gsr_median  gsr_variance  gsr_skewness  \
0      2019-11-21 09:35:29  1.355378    1.332223      0.000256      0.699293   
1      2019-11-21 09:35:30  1.339162    1.318903      0.000125     -0.100332   
2      2019-11-21 09:35:31  1.326166    1.306471      0.000135      0.010484   
3      2019-11-21 09:35:32  1.313587    1.294483      0.000113      0.140383   
4      2019-11-21 09:35:33  1.302077    1.286491      0.000085      0.139074   
...                    ...       ...         ...           ...           ...   
10286  2019-11-21 11:00:37  1.873922    1.857143      0.000018      1.241958   
10287  2019-11-21 11:00:38  1.872439    1.838095      0.000022      0.428993   
10288  2019-11-21 11:00:39  1.869794    1.838095      0.000021      0.490440   
10289  2019-11-21 11:00:40  1.866879    1.838095      0.000020      0.256191   
10290  2019-11-21 11:00:41  1.865581    1.842491      0.000017      0.676028   

       gsr_kurtosis    Act  
0         -0.627312  (0,0)  
1         -1.238669  (0,0)  
2         -1.243451  (0,0)  
3         -1.149240  (0,0)  
4         -1.145452  (0,0)  
...             ...    ...  
10286      5.575090  (2,3)  
10287      5.263945  (2,3)  
10288      4.582487  (2,3)  
10289      3.974350  (2,3)  
10290      4.517975  (2,3)  

[10291 rows x 11 columns]

In [4]:
print(df_keys)
len(df_keys)

Index(['Unnamed: 0', 'Unnamed: 0.1', 'GSR #', 'start_time', 'end_time',
       'gsr_mean', 'gsr_median', 'gsr_variance', 'gsr_skewness',
       'gsr_kurtosis', 'Act'],
      dtype='object')


11

In [5]:
# Data Preprocessing
df = df_feat.copy()
df = df.dropna()

Xs = df[df_keys[5:10]]
y = df['Act']

print(Xs)
print(y)

       gsr_mean  gsr_median  gsr_variance  gsr_skewness  gsr_kurtosis
0      1.355378    1.332223      0.000256      0.699293     -0.627312
1      1.339162    1.318903      0.000125     -0.100332     -1.238669
2      1.326166    1.306471      0.000135      0.010484     -1.243451
3      1.313587    1.294483      0.000113      0.140383     -1.149240
4      1.302077    1.286491      0.000085      0.139074     -1.145452
...         ...         ...           ...           ...           ...
10286  1.873922    1.857143      0.000018      1.241958      5.575090
10287  1.872439    1.838095      0.000022      0.428993      5.263945
10288  1.869794    1.838095      0.000021      0.490440      4.582487
10289  1.866879    1.838095      0.000020      0.256191      3.974350
10290  1.865581    1.842491      0.000017      0.676028      4.517975

[10291 rows x 5 columns]
0        (0,0)
1        (0,0)
2        (0,0)
3        (0,0)
4        (0,0)
         ...  
10286    (2,3)
10287    (2,3)
10288    (2,3)

In [6]:
# This is the data split

X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.2, random_state=10)

# Training the model
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [7]:
y_pred = classifier.predict(X_test)
print(y_pred)

['(1,2)' '(1,3)' '(2,1)' ... '(1,3)' '(1,1)' '(1,2)']


In [8]:
len(y_pred)

2059

In [9]:
len(y_test)

2059

In [10]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

[[ 17  19   8   3   0   3   1   2   0   1   0   0]
 [  5  95  60  19   0   6  14   7   0   5   2   5]
 [  1  62 109  14   1  16   9   2   0   2   5   2]
 [  6  40  29  56   1   7  12  16   0   4   5   2]
 [  1   2   8   4   1   7  10   2   1   1   5   2]
 [  6  17  11  19   1  67  18  23   0   7  14   8]
 [  2   9   5  12   4  20 173  23   2   9  37  12]
 [  3  16  12  17   0  38  28  49   3   6   9   6]
 [  1   3   2   3   0   7   8   4   0   6   6   4]
 [  0  12   8   4   1  18  15  24   6  35  21  10]
 [  1  14  11  18   1  17  69  27   5  18  89  15]
 [  1  13   7   9   0  28  35  13   3  15  34  15]]
              precision    recall  f1-score   support

       (0,0)       0.39      0.31      0.35        54
       (0,1)       0.31      0.44      0.37       218
       (0,2)       0.40      0.49      0.44       223
       (0,3)       0.31      0.31      0.31       178
       (1,0)       0.10      0.02      0.04        44
       (1,1)       0.29      0.35      0.32       191
       (

In [14]:
df_video = df.loc[(df.Act == "(0,0)") | (df.Act == "(0,1)") | (df.Act == "(0,2)") | (df.Act == "(0,3)")]

In [15]:
df_noeval = df.loc[(df.Act == "(1,0)") | (df.Act == "(1,1)") | (df.Act == "(1,2)") | (df.Act == "(1,3)")]

In [16]:
df_eval = df.loc[(df.Act == "(2,0)") | (df.Act == "(2,1)") | (df.Act == "(2,2)") | (df.Act == "(2,3)")]

In [19]:
def kNN(x):
    y = x.copy()
    df = y.dropna()

    Xs = df[df_keys[5:10]]
    y = df['Act']
    
    X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.2, random_state=10)

    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors=7)
    classifier.fit(X_train, y_train)
    
    y_pred = classifier.predict(X_test)
    
    from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(accuracy_score(y_test,y_pred))

In [20]:
kNN(df_video)

[[ 24  31   8   6]
 [  9 102  71  25]
 [  3  78 115  24]
 [  9  48  39  89]]
              precision    recall  f1-score   support

       (0,0)       0.53      0.35      0.42        69
       (0,1)       0.39      0.49      0.44       207
       (0,2)       0.49      0.52      0.51       220
       (0,3)       0.62      0.48      0.54       185

    accuracy                           0.48       681
   macro avg       0.51      0.46      0.48       681
weighted avg       0.50      0.48      0.49       681

0.4845814977973568


In [21]:
kNN(df_noeval)

[[  6  17  17   3]
 [  4 115  40  43]
 [  2  38 230  23]
 [  3  49  56  89]]
              precision    recall  f1-score   support

       (1,0)       0.40      0.14      0.21        43
       (1,1)       0.53      0.57      0.55       202
       (1,2)       0.67      0.78      0.72       293
       (1,3)       0.56      0.45      0.50       197

    accuracy                           0.60       735
   macro avg       0.54      0.49      0.49       735
weighted avg       0.59      0.60      0.58       735

0.5986394557823129


In [22]:
kNN(df_eval)

[[  4  10  12   9]
 [  9  80  50  30]
 [  3  30 202  44]
 [  3  22  77  59]]
              precision    recall  f1-score   support

       (2,0)       0.21      0.11      0.15        35
       (2,1)       0.56      0.47      0.51       169
       (2,2)       0.59      0.72      0.65       279
       (2,3)       0.42      0.37      0.39       161

    accuracy                           0.54       644
   macro avg       0.45      0.42      0.43       644
weighted avg       0.52      0.54      0.52       644

0.5357142857142857
