In [1]:
# CS 6316 ML Project: LASSO
# Created on Wed Apr 29 22:23 2020 
# @author: sl4bq

import time
import os
import shutil
import pandas as pd
from datetime import datetime
from dateutil import tz
import warnings
import itertools

import math
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split



In [2]:
# Remove the NaN rows and columns

def removeNaN(curr_feat_1, curr_feat_2):
    curr_feat_1_nan = np.array([])  # numpy.float64
    curr_feat_2_nan = np.array([])  # numpy.float64
    posi = 0
    # *** Check for and remove the Nan rows in from ONLY [curr_feat_2] feature rows
    for posi in range(len(curr_feat_2)):
        if not (math.isnan(curr_feat_2[posi])):# and not(math.isnan(curr_feat_1[posi]))):
            curr_feat_1_nan = np.append(curr_feat_1_nan, curr_feat_1[posi])
            curr_feat_2_nan = np.append(curr_feat_2_nan, curr_feat_2[posi])
            if (posi < 10):
                print(curr_feat_2_nan[posi])
        if (math.isnan(curr_feat_1[posi])):
            # curr_feat_1_nan = np.append(curr_feat_1_nan, curr_feat_1[posi])
            # curr_feat_2_nan = np.append(curr_feat_2_nan, curr_feat_2[posi])
            if (posi < 10):
                print(curr_feat_2_nan[posi])
    return curr_feat_1_nan, curr_feat_2_nan

#### Import .csv dataset into pandas
print('Importing Data Now')

#filename = '/Users/Mandala/PycharmProjects/ML_Project/windowing_results.csv'
filename = 'heart_rate_new.csv'

# Read data from csv file 
df_feat = pd.read_csv(filename)
df_keys = df_feat.keys()



Importing Data Now


In [3]:
df_feat

Unnamed: 0  GSR #           start_time             end_time  hr_mean  \
0     Heart_rate      1  2019-11-21 09:35:27  2019-11-21 09:35:31     -1.0   
1     Heart_rate      1  2019-11-21 09:35:29  2019-11-21 09:35:33     -1.0   
2     Heart_rate      1  2019-11-21 09:35:31  2019-11-21 09:35:35     -1.0   
3     Heart_rate      1  2019-11-21 09:35:33  2019-11-21 09:35:37     -1.0   
4     Heart_rate      1  2019-11-21 09:35:35  2019-11-21 09:35:39     -1.0   
...          ...    ...                  ...                  ...      ...   
5100  Heart_rate      6  2019-11-21 11:00:28  2019-11-21 11:00:32     -1.0   
5101  Heart_rate      6  2019-11-21 11:00:30  2019-11-21 11:00:34     -1.0   
5102  Heart_rate      6  2019-11-21 11:00:32  2019-11-21 11:00:36     -1.0   
5103  Heart_rate      6  2019-11-21 11:00:34  2019-11-21 11:00:38     -1.0   
5104  Heart_rate      6  2019-11-21 11:00:36  2019-11-21 11:00:40     -1.0   

      hr_std  hr_50% Activity  
0        0.0    -1.0    (0,0)  
1        0.0    -1.0    (0,0)  
2        0.0    -1.0    (0,0)  
3        0.0    -1.0    (0,0)  
4        0.0    -1.0    (0,0)  
...      ...     ...      ...  
5100     0.0    -1.0    (2,3)  
5101     0.0    -1.0    (2,3)  
5102     0.0    -1.0    (2,3)  
5103     0.0    -1.0    (2,3)  
5104     0.0    -1.0    (2,3)  

[5105 rows x 8 columns]

In [4]:
print(df_keys)
len(df_keys)

Index(['Unnamed: 0', 'GSR #', 'start_time', 'end_time', 'hr_mean', 'hr_std',
       'hr_50%', 'Activity'],
      dtype='object')


8

In [5]:
# Data Preprocessing
df = df_feat.copy()
df = df.dropna()

Xs = df[df_keys[4:7]]
y = df['Activity']

print(Xs)
print(y)

      hr_mean  hr_std  hr_50%
0        -1.0     0.0    -1.0
1        -1.0     0.0    -1.0
2        -1.0     0.0    -1.0
3        -1.0     0.0    -1.0
4        -1.0     0.0    -1.0
...       ...     ...     ...
5100     -1.0     0.0    -1.0
5101     -1.0     0.0    -1.0
5102     -1.0     0.0    -1.0
5103     -1.0     0.0    -1.0
5104     -1.0     0.0    -1.0

[5105 rows x 3 columns]
0       (0,0)
1       (0,0)
2       (0,0)
3       (0,0)
4       (0,0)
        ...  
5100    (2,3)
5101    (2,3)
5102    (2,3)
5103    (2,3)
5104    (2,3)
Name: Activity, Length: 5105, dtype: object


In [6]:
# This is the data split

X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.2, random_state=1)


In [7]:

# ---- Decision Tree -----------
from sklearn import tree

dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [8]:
y_pred = dt.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 3  3  0  0  0  0 21  0  0  2  0  0]
 [ 0 59  2  4  0  3 48  3  0  0  9  1]
 [ 0 19 18  8  2  3 57  6  2  2  8  5]
 [ 1 17  4 10  0  0 46  4  1  4  2  4]
 [ 0  0  2  0  4  0  5  1  0  0  3  1]
 [ 0  2  6  3  0 21 30  3  0  2 11  3]
 [ 0  1  7  4  1 11 89  2  1  7 12  3]
 [ 0  2  2  1  1  6 45 14  1  1  4  5]
 [ 0  0  1  1  0  1  6  1  2  0  2  1]
 [ 1  3  5  0  0  2 36  1  3 19  4  1]
 [ 2  4  7  7  1  9 67  8  4  8 28  7]
 [ 0  3  3  0  0 11 47  1  1  1  3 11]]
0.2722820763956905


In [11]:
df_video = df.loc[(df.Activity == "(0,0)") | (df.Activity == "(0,1)") | (df.Activity == "(0,2)") | (df.Activity == "(0,3)")]
df_noeval = df.loc[(df.Activity == "(1,0)") | (df.Activity == "(1,1)") | (df.Activity == "(1,2)") | (df.Activity == "(1,3)")]
df_eval = df.loc[(df.Activity == "(2,0)") | (df.Activity == "(2,1)") | (df.Activity == "(2,2)") | (df.Activity == "(2,3)")]

In [12]:
def DT(x):
    z = x.copy()
    df = z.dropna()

    Xs = df[df_keys[4:7]]
    y = df['Activity']
    
    X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.2, random_state=10)
    
    dt = tree.DecisionTreeClassifier()
    dt.fit(X_train, y_train)

    y_pred = dt.predict(X_test)

    print(confusion_matrix(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))

In [13]:
DT(df_video)

[[ 2  6  0 16]
 [ 0 55  7 41]
 [ 0 28 35 46]
 [ 1 25 15 61]]
0.4526627218934911


In [14]:
DT(df_noeval)

[[  4   1  13   2]
 [  5  31  53  11]
 [ 11  18 110   7]
 [  1  12  60  26]]
0.4684931506849315


In [15]:
DT(df_eval)

[[  3   6   8   2]
 [  2  10  49   7]
 [  1  19 111   5]
 [  3   8  71  14]]
0.43260188087774293
